[gh-actions]
python =
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314
    3.15: py315

[tox]
envlist =
    py3{11,12,13,14,15}-pytest90
    py3{11,12,13,14,15}-pytest91
    coverage

[testenv:coverage]
basepython = python3.15
recreate = true
deps =
    coverage[toml]>=7.6
commands =
    coverage combine
    coverage report
    coverage xml
    coverage html

[testenv:lint]
basepython = python3.15
recreate = true
deps =
    ruff

commands =
    python --version
    pip freeze
    ruff check

[testenv]
recreate = true
deps =
    pytest90: pytest>=9.0,<9.1
    pytest91: pytest>=9.1,<9.2
    pytest-xdist
    allure-python-commons-test
    coverage[toml]>=7.6

commands =
    python --version
    pip freeze
    coverage run -m pytest tests {posargs:}

setenv =
    ALLURE_INDENT_OUTPUT=1
    GLAMOR_TESTING_MODE=1


[pytest]
addopts =
    -x
    -r a
    -q
    -n auto
    --color yes
    --code-highlight yes
    --no-header
testpaths = tests